# assignment 02

## section A Data structures and control structures

### Q1 list of 5 integers ; operators append,extend,insert,remove,pop,clear,index,count,sort and reverse

In [7]:
lst1=[6,9,15,25,96]
# append
lst1.append(10)
print("lst1 after append:",lst1)

lst1 after append: [6, 9, 15, 25, 96, 10]

In [8]:
# extend
lst1.extend([22,12])
print("lst 1 after extend:",lst1)

lst 1 after extend: [6, 9, 15, 25, 96, 10, 22, 12]

In [9]:
# insert
lst1.insert(2,99)
print("lst1 after insert(2,99):",lst1)

lst1 after insert(2,99): [6, 9, 99, 15, 25, 96, 10, 22, 12]

In [10]:
# remove
lst1.remove(9)
print("lst1 after remove(9):",lst1)

lst1 after remove(9): [6, 99, 15, 25, 96, 10, 22, 12]

In [11]:
#pop
popped_value = lst1.pop()
print("after pop():",lst1)
print("popped values:",popped_value)

after pop(): [6, 99, 15, 25, 96, 10, 22]
popped values: 12

In [12]:
#index
index_value  = lst1.index(10)
print("index of 10:",index_value)

index of 10: 5

In [14]:
# count (to count no of terms)
count_value = lst1.count(2)
print("count of 2:",count_value)

count of 2: 0

In [15]:
#sort
lst1.sort()
print("lst1 after sort:",lst1)

lst1 after sort: [6, 10, 15, 22, 25, 96, 99]

In [17]:
#reverse
lst1.reverse()
print("after reverse:",lst1)

after reverse: [99, 96, 25, 22, 15, 10, 6]

In [18]:
#clear
lst1.clear()
print("after clear:",lst1)

after clear: []

### Q2 tuple to store 3 student names,change 2nd name in tuple

In [19]:
# creating a tuple to store 3 student names
students= ("LIKITH","MUNNA","ARUN")
print("student names:",students)

student names: ('LIKITH', 'MUNNA', 'ARUN')

In [20]:
# changing 2nd name
students[1]="spidy"

TypeError: 'tuple' object does not support item assignment

In [21]:
# here it shows the error, as tuple is immutable and doesnt support an item assignment as per the rules

### Q3 set of integers with some duplicate values

In [25]:
# creating a set with duplicates
num= {1,2,3,2,3,4,7,9,5,5}
num    #printing the set

{1, 2, 3, 4, 5, 7, 9}

In [26]:
# it doesnt print the duplicates as in sets the duplicates are automatically removed,as set stores only one unique value

### Q4 create dictionary with keys"name,"age","city",then update age and key email

In [29]:
#create a dictionary
man = {
    "name" : "Likith",
    "age":"21",
    "city":"Hyderabad"
}
print("real data:",man)
#updating age and key email
man["age"]=22
man["email"]= "likithlucky1525@gamil.com"
print("update information:",man)

real data: {'name': 'Likith', 'age': '21', 'city': 'Hyderabad'}
update information: {'name': 'Likith', 'age': 22, 'city': 'Hyderabad', 'email': 'likithlucky1525@gamil.com'}

In [30]:
print("final dictionary:",man)

final dictionary: {'name': 'Likith', 'age': 22, 'city': 'Hyderabad', 'email': 'likithlucky1525@gamil.com'}

### Q5 check whether a person is eligible or not for voting

In [31]:
# age as a variable
age = 22
if age>=18:
  print("eligible to vote")
else:
  print("not eligible for voting")

eligible to vote

### Q6 grade checker

In [34]:
marks = int(input("enter the marks"))
if marks>= 90:
  print("grade:A")
elif marks>= 75:
  print("grade:B")
elif marks>= 50:
  print("grade:C")
elif marks< 50:
  print("Fail")

enter the marks90
grade:A

### Q7 check a number is whther +ve & even

In [37]:
num = int(input("enter a number:"))
if num > 0:
  print("The number is positive")

  if num % 2 == 0:
    print("It is also an even number")
  else:
    print("It is odd number")
elif num == 0:
  print("The number is zero")
else:
  print("The number is negative")

enter a number:675767774
The number is positive
It is also an even number

## section B Numpy

### Q8 create

In [40]:
# scalar using numpy
import numpy as np
scalar = np.array(5)
print("scalar:",scalar)

scalar: 5

In [43]:
# 1D array with  values 1 to 5
array_1d = np.array([1,2,3,4,5])
print("1d array:",array_1d)

1d array: [1 2 3 4 5]

In [47]:
# 2D array with 2x3 values from 10 to 60 in steps of 10
array_2d = np.array([[10,20,30],
                    [40,50,60]])
print("array_2d:",array_2d)

array_2d: [[10 20 30]
 [40 50 60]]

### Q9 4x4 numpy array

In [53]:
array = np.random.randint(0,101, (4,4))
array

array([[  3,  69,  82,  24],
       [ 30,  93,  27,  75],
       [ 49,   2,  56,  25],
       [100,  92,   8,  27]])

### Q10 2d numy array 3x3 shape convert to pandas df and add columns a,b,c

In [54]:
import pandas as pd

In [57]:
array_Q10 = np.random.randint(0,11,(3,3))
array_Q10

array([[ 1,  5,  2],
       [ 7,  5,  1],
       [10,  5,  4]])

In [66]:
# coverting into pandas df
df_q10 = pd.DataFrame(array_Q10)
df_q10

    0  1  2
0   1  5  2
1   7  5  1
2  10  5  4

In [68]:
df_q10.columns= ["A","B","C"]   # renaming columns
df_q10

    A  B  C
0   1  5  2
1   7  5  1
2  10  5  4

## section C

### Q11

In [82]:
# Create DataFrame with 10 rows
data = {
    "Name": ["Likith", "Anita", "Kiran", "Sneha", "Arjun", "Priya", "Vikas", "Neha", "Rohit", "Anita"],
    "Age": [21, 22, 23, 21, 24, 22, 23, 21, 25, 22],
    "City": ["Hyderabad", "Mumbai", "Delhi", "Chennai", "Pune", "Kolkata", "Delhi", "Mumbai", "Pune", "Mumbai"],
    "Salary": [50000, 60000, np.nan, 55000, 70000, np.nan, 65000, 62000, 72000, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Info and Describe
print("\nInfo:")
df.info()

print("\nDescribe:")
print(df.describe())

# Select 'Name' and 'City'
selected = df[['Name', 'City']]
print("\nSelected Columns (Name & City):\n", selected)

# Drop 'City' column
df_dropped = df.drop(columns=['City'])
print("\nAfter Dropping 'City':\n", df_dropped)

# Fill missing Salary with mean
mean_salary = df['Salary'].mean()
df['Salary'].fillna(mean_salary, inplace=True)
print("\nAfter Filling Missing Salary:\n", df)

# Remove duplicate rows
df_no_duplicates = df.drop_duplicates()
print("\nAfter Removing Duplicates:\n", df_no_duplicates)

Original DataFrame:
      Name  Age       City   Salary
0  Likith   21  Hyderabad  50000.0
1   Anita   22     Mumbai  60000.0
2   Kiran   23      Delhi      NaN
3   Sneha   21    Chennai  55000.0
4   Arjun   24       Pune  70000.0
5   Priya   22    Kolkata      NaN
6   Vikas   23      Delhi  65000.0
7    Neha   21     Mumbai  62000.0
8   Rohit   25       Pune  72000.0
9   Anita   22     Mumbai  60000.0

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

Describe:
             Age        Salary
count  10.000000      8.000000
mean   22.400000  61750.000000
std     1.349897   7304.597378
min    21.000000  50000.000000
25%    21.250000  58750.000000
50%    22.000000  61000.000000
75%    23.000000  66250.000000
max    25.000000  72000.000000

Selected Columns (Name & City):
      Name       City
0  Likith  Hyderabad
1   Anita     Mumbai
2   Kiran      Delhi
3   Sneha    Chennai
4   Arjun       Pune
5   Priya    Kolkata
6   Vikas      Delhi
7    Neha     Mumbai
8   Rohit       Pune
9   Anita     Mumbai

After Dropping 'City':
      Name  Age   Salary
0  Likith   21  50000.0
1   Anita   22  60000.0
2   Kiran   23      NaN
3   Sneha   21  55000.0
4   Arjun   24  70000.0
5   Priya   22      NaN
6   Vikas   23  65000.0
7    Neha   21  62000.0
8   Rohit   25  72000.0
9   Anita   22  60000.0

After Filling Missing Salary:
      Name  Age       City   Salary
0  Likith   21  Hyderabad  50000.0
1   Anita   22     Mumbai  60000.0
2   Kiran   23      Delhi  61750.0
3   Sneha   21    Chennai  55000.0
4   Arjun   24       Pune  70000.0
5   Priya   22    Kolkata  61750.0
6   Vikas   23      Delhi  65000.0
7    Neha   21     Mumbai  62000.0
8   Rohit   25       Pune  72000.0
9   Anita   22     Mumbai  60000.0

After Removing Duplicates:
      Name  Age       City   Salary
0  Likith   21  Hyderabad  50000.0
1   Anita   22     Mumbai  60000.0
2   Kiran   23      Delhi  61750.0
3   Sneha   21    Chennai  55000.0
4   Arjun   24       Pune  70000.0
5   Priya   22    Kolkata  61750.0
6   Vikas   23      Delhi  65000.0
7    Neha   21     Mumbai  62000.0
8   Rohit   25       Pune  72000.0

/tmp/ipykernel_4075/1709244312.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(mean_salary, inplace=True)