# ASSIGNMENT 4

In [1]:
import numpy as np
import pandas as pd

In [11]:
df1 = pd.read_csv("Billing_Data.csv")

In [12]:
df1

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [24]:
df2 = pd.read_csv("Patient_Data.csv")
df2

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [18]:
# 1 load patient datset and info()
print("billing info:")
print(df1.info())
print("patient info:")
print(df2.info())

billing info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes
None
patient info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes
None

In [21]:
df2.describe()

        PatientID   BillAmount  ReceptionistID
count    6.000000     4.000000        6.000000
mean   102.666667  5925.000000        1.666667
std      1.632993  1192.686044        0.816497
min    101.000000  5000.000000        1.000000
25%    101.250000  5000.000000        1.000000
50%    102.500000  5600.000000        1.500000
75%    103.750000  6525.000000        2.000000
max    105.000000  7500.000000        3.000000

In [29]:
# 2 selecting columns for billing ["patient id","department","doctor","bill amount"]
df_selected = df2[["PatientID","Department","Doctor","BillAmount"]]
df_selected

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [32]:
# 3 Drop columns "receptionistid","checkin time"
df_clean = df2.drop(columns=["ReceptionistID","CheckinTime"],errors="ignore")
df_clean

   PatientID     Name   Department     Doctor  BillAmount       CheckInTime
0        101    Alice   Cardiology  Dr. Smith      5000.0  2023-01-10 09:00
1        102      Bob    Neurology   Dr. John         NaN  2023-01-11 10:30
2        103  Charlie  Orthopedics    Dr. Lee      7500.0  2023-01-12 11:00
3        104    David   Cardiology  Dr. Smith      6200.0  2023-01-13 12:00
4        105      Eva  Dermatology   Dr. Rose         NaN  2023-01-14 08:45
5        101    Alice   Cardiology  Dr. Smith      5000.0  2023-01-10 09:00

In [40]:
# 4 total bill amount per department
# 6 adding mean bill to all empty bills
mean_bill = df_clean["BillAmount"].mean()
df_clean["BillAmount"] = df_clean["BillAmount"].fillna(mean_bill)
df_clean

   PatientID     Name   Department     Doctor  BillAmount       CheckInTime
0        101    Alice   Cardiology  Dr. Smith      5000.0  2023-01-10 09:00
1        102      Bob    Neurology   Dr. John      5925.0  2023-01-11 10:30
2        103  Charlie  Orthopedics    Dr. Lee      7500.0  2023-01-12 11:00
3        104    David   Cardiology  Dr. Smith      6200.0  2023-01-13 12:00
4        105      Eva  Dermatology   Dr. Rose      5925.0  2023-01-14 08:45

In [41]:
#5 remove duplicate patients details
df_clean = df_clean.drop_duplicates(subset="PatientID")
df_clean

   PatientID     Name   Department     Doctor  BillAmount       CheckInTime
0        101    Alice   Cardiology  Dr. Smith      5000.0  2023-01-10 09:00
1        102      Bob    Neurology   Dr. John      5925.0  2023-01-11 10:30
2        103  Charlie  Orthopedics    Dr. Lee      7500.0  2023-01-12 11:00
3        104    David   Cardiology  Dr. Smith      6200.0  2023-01-13 12:00
4        105      Eva  Dermatology   Dr. Rose      5925.0  2023-01-14 08:45

In [43]:
# 4 groupby total per department
dept_total = df_clean.groupby("Department")["BillAmount"].sum()
dept_total

Department
Cardiology     11200.0
Dermatology     5925.0
Neurology       5925.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [47]:
# 7 merge billing dataset with patient dataset on "PatientID"
df_merged = pd.merge(df_clean, df1, on="PatientID", how="inner")
df_merged

,PatientID,Name,Department,Doctor,BillAmount,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2023-01-10 09:00,2000,3000
1,102,Bob,Neurology,Dr. John,5925.0,2023-01-11 10:30,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2023-01-12 11:00,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,2023-01-13 12:00,3000,3200
4,105,Eva,Dermatology,Dr. Rose,5925.0,2023-01-14 08:45,1000,4000

In [49]:
# 8 add new weekly patient row wise
new_patients = pd.DataFrame({
    'PatientID': [106, 107],
    'Name': ['Rahul', 'Sneha'],
    'Department': ['Cardiology', 'Neurology'],
    'Doctor': ['Dr. Smith', 'Dr. John'],
    'BillAmount': [5500, 4800]
})
df_final = pd.concat([df_merged, new_patients], axis=0, ignore_index=True)
new_patients

   PatientID   Name  Department     Doctor  BillAmount
0        106  Rahul  Cardiology  Dr. Smith        5500
1        107  Sneha   Neurology   Dr. John        4800

In [50]:
# add new billing columns columns wise
new_billing_cols = pd.DataFrame({
    'InsuranceCovered': [1200, 1800],
    'FinalAmount': [4300, 3000]
})
new_billing_cols

   InsuranceCovered  FinalAmount
0              1200         4300
1              1800         3000

In [58]:
new_billing_cols = new_billing_cols.reindex(df_final.index)

df_final = pd.concat([df_final, new_billing_cols], axis=1)
df_final

,PatientID,Name,Department,Doctor,BillAmount,CheckInTime,InsuranceCovered,FinalAmount,InsuranceCovered,FinalAmount,InsuranceCovered,FinalAmount,InsuranceCovered,FinalAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2023-01-10 09:00,2000.0,3000.0,1200.0,4300.0,1200.0,4300.0,1200.0,4300.0,1200.0,4300.0
1,102,Bob,Neurology,Dr. John,5925.0,2023-01-11 10:30,1500.0,3500.0,1800.0,3000.0,1800.0,3000.0,1800.0,3000.0,1800.0,3000.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2023-01-12 11:00,2500.0,5000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,104,David,Cardiology,Dr. Smith,6200.0,2023-01-13 12:00,3000.0,3200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105,Eva,Dermatology,Dr. Rose,5925.0,2023-01-14 08:45,1000.0,4000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,106,Rahul,Cardiology,Dr. Smith,5500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,107,Sneha,Neurology,Dr. John,4800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
print("Final Cleaned Dataset:")
print(df_final)

Final Cleaned Dataset:
   PatientID     Name   Department     Doctor  BillAmount       CheckInTime  \
0        101    Alice   Cardiology  Dr. Smith      5000.0  2023-01-10 09:00
1        102      Bob    Neurology   Dr. John      5925.0  2023-01-11 10:30
2        103  Charlie  Orthopedics    Dr. Lee      7500.0  2023-01-12 11:00
3        104    David   Cardiology  Dr. Smith      6200.0  2023-01-13 12:00
4        105      Eva  Dermatology   Dr. Rose      5925.0  2023-01-14 08:45
5        106    Rahul   Cardiology  Dr. Smith      5500.0               NaN
6        107    Sneha    Neurology   Dr. John      4800.0               NaN

   InsuranceCovered  FinalAmount  InsuranceCovered  FinalAmount  \
0            2000.0       3000.0            1200.0       4300.0
1            1500.0       3500.0            1800.0       3000.0
2            2500.0       5000.0               NaN          NaN
3            3000.0       3200.0               NaN          NaN
4            1000.0       4000.0               NaN          NaN
5               NaN          NaN               NaN          NaN
6               NaN          NaN               NaN          NaN

   InsuranceCovered  FinalAmount  InsuranceCovered  FinalAmount  \
0            1200.0       4300.0            1200.0       4300.0
1            1800.0       3000.0            1800.0       3000.0
2               NaN          NaN               NaN          NaN
3               NaN          NaN               NaN          NaN
4               NaN          NaN               NaN          NaN
5               NaN          NaN               NaN          NaN
6               NaN          NaN               NaN          NaN

   InsuranceCovered  FinalAmount
0            1200.0       4300.0
1            1800.0       3000.0
2               NaN          NaN
3               NaN          NaN
4               NaN          NaN
5               NaN          NaN
6               NaN          NaN

In [60]:
df_final

,PatientID,Name,Department,Doctor,BillAmount,CheckInTime,InsuranceCovered,FinalAmount,InsuranceCovered,FinalAmount,InsuranceCovered,FinalAmount,InsuranceCovered,FinalAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2023-01-10 09:00,2000.0,3000.0,1200.0,4300.0,1200.0,4300.0,1200.0,4300.0,1200.0,4300.0
1,102,Bob,Neurology,Dr. John,5925.0,2023-01-11 10:30,1500.0,3500.0,1800.0,3000.0,1800.0,3000.0,1800.0,3000.0,1800.0,3000.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2023-01-12 11:00,2500.0,5000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,104,David,Cardiology,Dr. Smith,6200.0,2023-01-13 12:00,3000.0,3200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105,Eva,Dermatology,Dr. Rose,5925.0,2023-01-14 08:45,1000.0,4000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,106,Rahul,Cardiology,Dr. Smith,5500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,107,Sneha,Neurology,Dr. John,4800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN